extends Node2D

const VIRTUAL_CONTROLS := preload("res://scripts/virtual_controls.gd")
const MOBILE_ORIENTATION := preload("res://scripts/mobile_orientation.gd")
const UI_PROGRESS_METER := preload("res://scripts/ui_progress_meter.gd")
const GAME_BATTLE_UI := preload("res://scripts/game_battle_ui.gd")
const DIALOGUE_CONTROLLER := preload("res://scripts/game/ui/dialogue_controller.gd")
const MAP_TRANSITION_CONTROLLER := preload("res://scripts/game/world/map_transition_controller.gd")
const CYBER_TELEPORT_CONTROLLER := preload("res://scripts/game/world/cyber_teleport_controller.gd")
const WORLD_RENDERER := preload("res://scripts/game/world/world_renderer.gd")
const TRADE_CONTROLLER := preload("res://scripts/game/trade/trade_controller.gd")
const LEARNING_CONTROLLER := preload("res://scripts/game/skills/learning_controller.gd")
const PRACTICE_CONTROLLER := preload("res://scripts/game/skills/practice_controller.gd")
const NPC_WORLD_CONTROLLER := preload("res://scripts/game/world/npc_world_controller.gd")
const HUD_VIEWS := preload("res://scripts/game/ui/hud_views.gd")
const INVENTORY_SKILLBOOK_CONTROLLER := preload("res://scripts/game/inventory/inventory_skillbook_controller.gd")
const MENU_CONTROLLER := preload("res://scripts/game/menu/menu_controller.gd")
const INTERACTION_CONTROLLER := preload("res://scripts/game/interaction/interaction_controller.gd")
const GAME_RUNTIME_CONTROLLER := preload("res://scripts/game/runtime/game_runtime_controller.gd")
const HUD_LAYOUT := preload("res://scripts/game/ui/hud_layout.gd")
const CAMERA_SIZE := Vector2(480.0, 320.0)
const DESIGN_SIZE := CAMERA_SIZE
const MOVE_STEP_SECONDS := 0.15
const DIALOGUE_AUTO_CLOSE_MSEC := 5000
const TRADE_MODE_BUY := "buy"
const TRADE_MODE_SELL := "sell"
const CYBER_TELEPORT_SKILL_REQUIREMENT := 30

var player_tile := Vector2i(8, 5)
var facing := Vector2i.RIGHT
var move_cooldown := 0.0
var message := "欢迎来到开源镇"
@onready var map_renderer: TiledMapRenderer = $MapRenderer
@onready var map_badge_panel: PanelContainer = $HUD/MapBadge
@onready var map_badge: Label = $HUD/MapBadge/Content
@onready var transition_overlay: ColorRect = $HUD/Transition
@onready var hud: CanvasLayer = $HUD
@onready var menu_panel: PanelContainer = $HUD/Menu
@onready var menu_content: Label = $HUD/Menu/Content
@onready var menu_items: Control = $HUD/Menu/Items
@onready var skill_menu_panel: PanelContainer = $HUD/SkillMenu
@onready var skill_menu_items: Control = $HUD/SkillMenu/Items
@onready var system_menu_panel: PanelContainer = $HUD/SystemMenu
@onready var system_menu_items: Control = $HUD/SystemMenu/Items
@onready var battle_panel: PanelContainer = $HUD/Battle
@onready var battle_content: Label = $HUD/Battle/Content
@onready var details_panel: PanelContainer = $HUD/NpcViewHUD
@onready var details_content: Label = $HUD/NpcViewHUD/Content
@onready var npc_portrait: TextureRect = $HUD/NpcViewHUD/Content/Portrait
@onready var dialogue_panel: PanelContainer = $HUD/Dialogue
@onready var dialogue_content: Label = $HUD/Dialogue/Content
@onready var tree_confirm_panel: PanelContainer = $HUD/TreeConfirm
@onready var tree_confirm_content: Label = $HUD/TreeConfirm/Content
@onready var npc_menu_panel: PanelContainer = $HUD/NpcMenu
@onready var npc_menu_content: Label = $HUD/NpcMenu/Content
var nearby_npc_id := ""
var map_context: TiledMapLoader
var menu_open := false
var menu_index := 0
var system_open := false
var system_index := 0
var skill_open := false
var skill_index := 0
var force_power_open := false
var force_power_value := 0
var force_power_limit := 0
var menu_widgets: Array[Control] = []
var details_widgets: Array[Control] = []
var detail_huds: Dictionary = {}
var detail_widget_sets: Dictionary = {}
var active_detail_hud := "generic"
var profile_panel_open := false
var npc_view_panel_open := false
var battle_ui: RefCounted
var cyber_open := false
var cyber_index := 0
var cyber_maps: Array[int] = []
var cyber_labels: Array[Label] = []
var cyber_selection_widget: Panel
var npc_menu_open := false
var npc_menu_index := 0
var npc_menu_actions: Array[String] = []
var npc_menu_labels: Array[String] = []
var npc_menu_widgets: Array[Control] = []
var trade_open := false
var trade_mode := TRADE_MODE_BUY
var trade_index := 0
var trade_items: Array = []
var trade_all_items: Array = []
var trade_categories: Array[String] = []
var trade_category_index := 0
var trade_focus_category := true
var learn_open := false
var learn_index := 0
var learn_items: Array[String] = []
var learn_all_items: Array[String] = []
var learn_categories: Array[String] = []
var learn_category_index := 0
var learn_focus_category := true
var learning_skill_id := ""
var learning_tick_accumulator := 0.0
var inventory_open := false
var inventory_items: Array[String] = []
var inventory_categories: Array[String] = ["食物", "药物", "武器", "防具", "鞋子", "饰品", "其他", "丢弃"]
var inventory_category_index := 0
var inventory_index := 0
var inventory_focus_category := true
var inventory_feedback := ""
var practice_open := false
var practice_index := 0
var practice_items: Array[String] = []
var practice_all_items: Array[String] = []
var practice_categories: Array[String] = ["编码", "思维", "招架"]
var practice_themes: Array[String] = ["code", "tune", "parry"]
var practice_category_index := 0
var practice_focus_category := true
var practicing_skill_id := ""
var practice_tick_accumulator := 0.0
var skill_book_open := false
var skill_book_categories: Array[String] = ["编码", "思维", "架构", "招架", "灵感"]
var skill_book_category_index := 0
var skill_book_focus_category := true
var skill_book_items: Array[String] = []
var skill_book_index := 0
var meditation_open := false
var meditation_widgets: Array[Control] = []
var learning_progress_widgets: Array[Control] = []
var practice_progress_widgets: Array[Control] = []
var meditation_tick_accumulator := 0.0
var SKILL_BOOK_THEMES: Array[String] = ["code", "tune", "arch", "parry", "knowledge"]
var dialogue_open := false
var dialogue_pages: Array[String] = []
var dialogue_page_index := 0
var dialogue_speaker := ""
var dialogue_locked_until_msec := 0
var dialogue_auto_close_at_msec := 0
var dialogue_after_last := Callable()
var dialogue_controller := DIALOGUE_CONTROLLER.new(self)
var map_transition_controller := MAP_TRANSITION_CONTROLLER.new(self)
var cyber_teleport_controller := CYBER_TELEPORT_CONTROLLER.new(self)
var world_renderer := WORLD_RENDERER.new(self)
var trade_controller := TRADE_CONTROLLER.new(self)
var learning_controller := LEARNING_CONTROLLER.new(self)
var practice_controller := PRACTICE_CONTROLLER.new(self)
var npc_world_controller := NPC_WORLD_CONTROLLER.new(self)
var hud_views := HUD_VIEWS.new(self)
var inventory_skillbook_controller := INVENTORY_SKILLBOOK_CONTROLLER.new(self)
var menu_controller := MENU_CONTROLLER.new(self)
var interaction_controller := INTERACTION_CONTROLLER.new(self)
var game_runtime_controller := GAME_RUNTIME_CONTROLLER.new(self)
var hud_layout := HUD_LAYOUT.new(self)
var map_transitioning := false
var has_loaded_map := false
var delete_confirm_open := false
var delete_confirm_index := 1
var map_index := 0
var player_texture: Texture2D = preload("res://assets/Texture/player.png")
var npc_texture: Texture2D = preload("res://assets/Texture/NPC.png")
var player_sprite_regions: Dictionary = {}
var player_sprite_layouts: Dictionary = {}
var animation_timer := 0.0
var animation_frame := 0
var player_moving := false
var virtual_direction := Vector2.ZERO
var accept_requested := false
var cancel_requested := false
var auto_save_timer := 0.0
var last_layout_viewport_size := Vector2.ZERO
const MENU_ITEMS := ["查看", "背包", "技能", "系统"]
const SKILL_ITEMS := ["冥想", "练功", "加力", "功法"]
const SYSTEM_ITEMS := ["赛博传送", "摸鱼", "疗伤", "保存", "退出"]
