export const DEFAULT_WORKBOOK = 'docs/data/FrontendLegendsData.xlsx';
export const DATA_DIR = 'assets/Data';
export const DATA_FILES = ['items', 'skills', 'npcs', 'quests', 'world_events'];

export const SHEETS = {
  meta: 'Meta',
  readme: 'README',
  balanceRules: 'BalanceRules',
  items: 'Items',
  vendorStock: 'VendorStock',
  skills: 'Skills',
  teachStock: 'TeachStock',
  npcs: 'NPCs',
  npcSkillLevels: 'NPCSkillLevels',
  npcEquipment: 'NPCEquipment',
  npcLoot: 'NPCLoot',
  quests: 'Quests',
  worldEventTypes: 'WorldEventTypes',
  worldEvents: 'WorldEvents',
};

export const HEADERS = {
  [SHEETS.meta]: ['file', 'version', 'note', 'configJson'],
  [SHEETS.balanceRules]: ['category', 'key', 'value', 'formula', 'notes'],
  [SHEETS.items]: [
    'itemId', 'name', 'kind', 'slot', 'price',
    'rarity', 'weight', 'stackLimit', 'unique', 'discardable', 'consumeOnUse',
    'tags', 'questId', 'source',
    'effectFood', 'effectWater', 'effectHp', 'effectInjury', 'effectAppearance', 'effectPotential',
    'bonusAttack', 'bonusDefense', 'bonusHit', 'bonusDodge', 'bonusCrit', 'bonusParry', 'bonusWoundInflict',
    'skillId', 'maxLearnLevel',
    'attrStrength', 'attrAgility', 'attrConstitution', 'attrWisdom',
    'reqStrength', 'reqAgility', 'reqConstitution', 'reqWisdom',
    'sellable', 'description', 'configJson',
  ],
  [SHEETS.vendorStock]: ['npcId', 'itemId', 'sort'],
  [SHEETS.skills]: [
    'skillId', 'name', 'category', 'sect', 'tier', 'theme', 'maxLevel',
    'costBase', 'costFactor', 'reqSect', 'reqStrength', 'reqAgility',
    'reqConstitution', 'reqWisdom', 'reqMinSkillPower', 'reqMinAvgSkill',
    'prereqSkillId', 'prereqLevel', 'atkPerLv', 'defPerLv', 'hitPerLv',
    'dodgePerLv', 'parryPerLv', 'injuryReducePerLv', 'mpMaxPerLv', 'mpCost',
    'description', 'configJson',
  ],
  [SHEETS.teachStock]: ['npcId', 'skillId', 'maxTeachLevel', 'sort'],
  [SHEETS.npcs]: [
    'npcId', 'displayName', 'gender', 'age', 'sprite', 'roles', 'sect', 'title', 'money',
    'combatRank', 'combatRole', 'targetableByKillQuest',
    'description', 'defaultLine',
    'attrStrength', 'attrAgility', 'attrConstitution', 'attrWisdom',
    'joinStrength', 'joinAgility', 'joinConstitution', 'joinWisdom',
    'combatHpMax', 'combatHp', 'combatMpMax', 'combatMp',
    'rewardExperience', 'rewardPotential', 'rewardMoney', 'inventory', 'configJson',
  ],
  [SHEETS.npcSkillLevels]: ['npcId', 'skillId', 'level', 'equipped', 'sort'],
  [SHEETS.npcEquipment]: ['npcId', 'itemId', 'sort'],
  [SHEETS.npcLoot]: ['npcId', 'itemId', 'chance', 'min', 'max', 'sort'],
  [SHEETS.quests]: ['bucket', 'questId', 'type', 'title', 'configJson'],
  [SHEETS.worldEventTypes]: [
    'archetype', 'action', 'displayName', 'amount',
    'prompt', 'acceptLabel', 'cancelLabel', 'configJson',
  ],
  [SHEETS.worldEvents]: [
    'eventId', 'mapId', 'archetype', 'tileX', 'tileY', 'width', 'height',
    'displayName', 'text', 'questEndpoint', 'configJson',
  ],
};

export const BALANCE_RULE_ROWS = [
  { category: '目标', key: '非战斗单位', value: '均衡新手1次有效命中、攻击尝试P90≤2；极端低编码中位4/P90 6次攻击尝试', formula: '', notes: '儿童、商贩等不靠堆血延长战斗' },
  { category: '目标', key: '同属性同功法镜像战', value: '8–12 回合', formula: '双方同四维、同功法；无闪避/装备/道具/加力/主动招式；每回合至多各命中一次普攻', notes: '保留暴击、完整功法被动招架、减伤和±10%伤害浮动' },
  { category: '校准', key: '四门派镜像 P10/中位/P90', value: 'L0 8/8/9；L20 8–9/9/10；L60 8–9/9–10/10–11；L100 8–9/9–10/10–11', formula: 'NG / React / Vue / Vanilla，各等级10,000次随机模拟', notes: '16组P10、中位与P90全部位于8–12回合' },
  { category: '目标', key: '精英 / Boss', value: '8–12 / 10–14 个决策', formula: '', notes: '通过技能与阶段而非无限回血延长' },
  { category: '基础', key: '攻击', value: '', formula: 'floor(10 + 编码×1.8×centeredScale(编码,0.004,0.90,1.10))', notes: '再加功法与装备攻击' },
  { category: '基础', key: '防御', value: '', formula: 'floor(架构×1.2×centeredScale(架构,0.003,0.92,1.08))', notes: '再加功法与装备防御' },
  { category: '资源', key: '体力上限', value: '', formula: '186 + 架构×6 + floor(sqrt(精力上限)×3)', notes: '以生命池承载8–12回合基准；精力仍只按平方根反哺体力' },
  { category: '资源', key: '玩家精力上限', value: '', formula: '精力修为 + 装备功法 mpMaxPerLv 加成', notes: '功法上限字段已接入运行时' },
  { category: '资源', key: 'NPC精力上限', value: '', formula: 'floor(内功值×25×架构修正) + 装备功法 mpMaxPerLv 加成', notes: 'NPC 内功值来自基础架构与已装备门派架构功法' },
  { category: '判定', key: '命中率', value: '45%–95%', formula: 'clamp(78% + (攻方思维-守方思维)×1.2% + 命中加成 - 闪避加成)', notes: '减少连续空回合' },
  { category: '判定', key: '减伤率', value: '', formula: '防御/(防御+100)', notes: '递减收益' },
  { category: '判定', key: '招架率', value: '0%–55%', formula: 'clamp(4% + 编码×0.4% + 功法/装备招架)', notes: '招架后保留 60% 伤害' },
  { category: '判定', key: '暴击率', value: '2%–30%', formula: 'clamp(3% + 思维×0.15% + 灵感×0.15% + 装备暴击)', notes: '架构不再负责暴击' },
  { category: '技能', key: '招式触发', value: '攻击≤45%；闪避≤27%；招架≤35%', formula: '各类型使用独立 base + count×perMove', notes: '避免多层完全回避锁死战斗' },
  { category: '技能', key: '加力', value: '额外伤害≤75%', formula: '伤害×min(75%, 加力/(加力+100))×随机0.9–1.1', notes: '递减收益，不再直接平铺数百点' },
  { category: 'AI', key: 'NPC 加力', value: '默认 45% 概率、25% 内功', formula: '可由 ai.forceUseRate / forceRatio 覆盖', notes: '高阶人物有爆发但不再每击全力' },
  { category: 'AI', key: 'NPC 摸鱼', value: '默认每战 1 次，最多回 18%', formula: '体力低于35%且精力足够时20%概率', notes: '不会反复重置血条' },
  { category: '恢复', key: '玩家摸鱼 / 用药', value: '每战 1 次 / 2 次', formula: '摸鱼最多恢复20%最大体力', notes: '受保护 HUD 未改，以次数上限约束免费动作' },
  { category: '伤势', key: '战后伤势', value: '单场≤真实体力20%', formula: '净体力损失×15%×(1-功法伤势减免) + 当场重伤', notes: '不按累计受击重复惩罚治疗' },
  { category: '伤势', key: '破相判定', value: '濒死15%；归零30%；每次容貌−20', formula: '两项独立判定且可叠加，仅致命战斗触发', notes: '容貌永久损失会写入角色状态' },
  { category: '战败', key: '资源与功法惩罚', value: '经验/潜能/Token各−5%～10%；25%概率最多一门功法−1级', formula: '三类资源分别随机5%～10%；仅从高于保底等级的已学功法中随机一门', notes: '结算后立即重算派生属性与体力/精力上限' },
  { category: '成长', key: '学习需求', value: '满级单级跨度4', formula: '二次曲线，灵感倍率65%–125%，结果向上取偶数', notes: '旧跨度20下调，减少重复任务量' },
  { category: '任务', key: '环任务成长', value: '线性且封顶', formula: '1 + ringGrowth×(环数-1)，再受 growthCap 限制', notes: '悬赏奖励也改为基于初始值线性成长' },
  { category: '任务', key: '奖励互斥', value: '任务奖励或野战奖励二选一', formula: '普通悬赏击杀先标记完成，回程交付时才发奖', notes: '防止同一目标重复获得两份奖励' },
  { category: '任务', key: '交付物退款', value: '固定成本补偿', formula: '物品价格×itemRefundRate', notes: '退款不参与环数成长或随机浮动，服务费才属于奖励' },
  { category: '任务', key: '并行任务状态', value: '不同任务可同时活动', formula: '固定任务按 quest_id；生成任务按 generator:<generator_id> 唯一', notes: '同一 runtime_id/生成器不可重复；任务仅存本局内存，重开或读档时清空' },
  { category: '任务', key: '随机目标过滤', value: '保护任务端点、非战斗与剧情人物', formula: '排除全部任务发布/交付端点、当前目标；击杀池另排除未满18岁、noncombatant、商贩、典当商、师父、显式保护人物', notes: '只有悬赏/击杀环响应击败事件，跑腿与谈话任务必须交付' },
  { category: '人物', key: 'combatRank', value: 'noncombatant→legendary 共7档', formula: '仅缩放生命池与普通奖励', notes: '攻击、防御仍来自显式四维、功法、装备' },
  { category: '人物', key: 'combatRank 生命倍率', value: '0.24 / 0.78 / 0.92 / 1.00 / 1.10 / 1.20 / 1.30', formula: 'noncombatant / novice / trained / veteran / elite / master / legendary', notes: '小学生为 noncombatant：2架构、0精力时最终48体力' },
  { category: '人物', key: 'combatRank 奖励倍率', value: '0.15 / 0.50 / 0.75 / 1.00 / 1.20 / 1.50 / 2.00', formula: 'noncombatant / novice / trained / veteran / elite / master / legendary', notes: '战斗奖励与生命倍率分离，非战斗人物不成为刷取目标' },
  { category: '人物', key: 'combatRole', value: '7种原型', formula: 'noncombatant/striker/skirmisher/tank/counter/controller/balanced', notes: '66 人四维配点全部唯一且总点数不变' },
  { category: '状态', key: '资源归一化', value: '上限变化即时钳制', formula: '卸功法或战败降级后重算四维、体力与精力上限', notes: '不允许保存当前值高于新上限' },
  { category: '存档', key: 'v2/v3→v4', value: '按比例迁移', formula: '旧体力/伤势按比例映射；v2 仅有证据时按双倍精力折半', notes: '兼容 v2 中途未升版本便改为1:1精力的历史存档' },
];
