export const DEFAULT_WORKBOOK_DIR = 'docs/data';
export const DATA_DIR = 'assets/Data';
export const DATA_FILES = ['items', 'skills', 'npcs', 'quests', 'world_events', 'maps'];

export const SHEETS = {
  meta: 'Meta',
  readme: 'README',
  balanceRules: 'BalanceRules',
  items: 'Items',
  vendorStock: 'VendorStock',
  skills: 'Skills',
  teachStock: 'TeachStock',
  npcs: 'NPCs',
  npcSkillLevels: 'NPCSkillLevels',
  npcEquipment: 'NPCEquipment',
  npcLoot: 'NPCLoot',
  quests: 'Quests',
  worldEventTypes: 'WorldEventTypes',
  worldEvents: 'WorldEvents',
  maps: 'Maps',
};

export const WORKBOOKS = {
  items: { file: 'items.xlsx', dataFile: 'items', title: '道具数据', sheets: [SHEETS.items, SHEETS.vendorStock] },
  skills: { file: 'skills.xlsx', dataFile: 'skills', title: '技能数据', sheets: [SHEETS.skills, SHEETS.teachStock] },
  npcs: {
    file: 'npcs.xlsx', dataFile: 'npcs', title: 'NPC 数据',
    sheets: [SHEETS.npcs, SHEETS.npcSkillLevels, SHEETS.npcEquipment, SHEETS.npcLoot],
  },
  quests: { file: 'quests.xlsx', dataFile: 'quests', title: '任务数据', sheets: [SHEETS.quests] },
  world_events: {
    file: 'world-events.xlsx', dataFile: 'world_events', title: '世界事件数据',
    sheets: [SHEETS.worldEventTypes, SHEETS.worldEvents],
  },
  maps: { file: 'maps.xlsx', dataFile: 'maps', title: '地图索引数据', sheets: [SHEETS.maps] },
  balance: { file: 'balance-rules.xlsx', dataFile: null, title: '平衡规则', sheets: [SHEETS.balanceRules] },
};

export const HEADERS = {
  [SHEETS.meta]: ['file', 'version', 'note', 'configJson'],
  [SHEETS.balanceRules]: ['category', 'key', 'value', 'formula', 'notes'],
  [SHEETS.items]: [
    'itemId', 'name', 'kind', 'slot', 'price',
    'rarity', 'weight', 'stackLimit', 'unique', 'discardable', 'consumeOnUse',
    'tags', 'questId', 'source',
    'effectFood', 'effectWater', 'effectHp', 'effectInjury', 'effectAppearance', 'effectPotential',
    'bonusAttack', 'bonusDefense', 'bonusHit', 'bonusDodge', 'bonusCrit', 'bonusParry', 'bonusWoundInflict',
    'skillId', 'maxLearnLevel',
    'attrStrength', 'attrAgility', 'attrConstitution', 'attrWisdom',
    'reqStrength', 'reqAgility', 'reqConstitution', 'reqWisdom',
    'sellable', 'description', 'configJson',
  ],
  [SHEETS.vendorStock]: ['npcId', 'itemId', 'sort'],
  [SHEETS.skills]: [
    'skillId', 'name', 'category', 'sect', 'tier', 'theme', 'maxLevel',
    'costBase', 'costFactor', 'reqSect', 'reqStrength', 'reqAgility',
    'reqConstitution', 'reqWisdom', 'reqMinSkillPower', 'reqMinAvgSkill',
    'prereqSkillId', 'prereqLevel', 'atkPerLv', 'defPerLv', 'hitPerLv',
    'dodgePerLv', 'parryPerLv', 'injuryReducePerLv', 'mpMaxPerLv', 'mpCost',
    'description', 'configJson',
  ],
  [SHEETS.teachStock]: ['npcId', 'skillId', 'maxTeachLevel', 'sort'],
  [SHEETS.npcs]: [
    'npcId', 'displayName', 'gender', 'age', 'sprite', 'roles', 'sect', 'title', 'money',
    'combatRank', 'combatRole', 'targetableByKillQuest',
    'description', 'defaultLine',
    'attrStrength', 'attrAgility', 'attrConstitution', 'attrWisdom',
    'joinStrength', 'joinAgility', 'joinConstitution', 'joinWisdom',
    'combatHpMax', 'combatHp', 'combatMpMax', 'combatMp',
    'rewardExperience', 'rewardPotential', 'rewardMoney', 'inventory', 'configJson',
  ],
  [SHEETS.npcSkillLevels]: ['npcId', 'skillId', 'level', 'equipped', 'sort'],
  [SHEETS.npcEquipment]: ['npcId', 'itemId', 'sort'],
  [SHEETS.npcLoot]: ['npcId', 'itemId', 'chance', 'min', 'max', 'sort'],
  [SHEETS.quests]: ['bucket', 'questId', 'type', 'title', 'configJson'],
  [SHEETS.worldEventTypes]: [
    'archetype', 'action', 'displayName', 'amount',
    'prompt', 'acceptLabel', 'cancelLabel', 'configJson',
  ],
  [SHEETS.worldEvents]: [
    'eventId', 'mapId', 'archetype', 'tileX', 'tileY', 'width', 'height',
    'displayName', 'text', 'questEndpoint', 'configJson',
  ],
  [SHEETS.maps]: ['mapId', 'path', 'displayName', 'mapType', 'parentMapId', 'configJson'],
};

export const BALANCE_RULE_ROWS = [
  { category: '不变量', key: '学习资源与阶段', value: '潜能→灵感转换→固定学习经验满→按实际潜能支付Token→升级', formula: '数值与公式可调；资源身份和阶段顺序不可擅改', notes: '固定经验不读取灵感、每级增长且始终为偶数；结构修改需用户后续明确确认' },
  { category: '不变量', key: '战斗输入与职责', value: '四属性+已装备功法+装备+状态/伤势/精力/加力/主动招式', formula: '玩家与NPC同口径聚合，combatRank仅缩放NPC体力与普通奖励', notes: '不得删除输入、交换四属性职责、让未装备功法生效或加入隐藏倍率' },
  { category: '治理', key: '修改授权边界', value: '数值、系数、阈值和计算公式可调', formula: '结构修改先列出文件/行为/存档数据/测试影响，再等待一次性确认', notes: '首次提出不视为授权；测试通过不能替代用户确认' },
  { category: '目标', key: '非战斗单位', value: '均衡新手中位2–4/P90≤5；低编码合法新手中位6–9/P90≤12次攻击尝试', formula: '', notes: '小学生固定100体力，不再被普通攻击一击击倒' },
  { category: '目标', key: '同属性同功法镜像战', value: '8–12 回合', formula: '双方同四维、同功法；无闪避/装备/道具/加力/主动招式；每回合至多各命中一次普攻', notes: '保留暴击、完整功法被动招架、减伤和±10%伤害浮动' },
  { category: '校准', key: '四门派镜像 P10/中位/P90', value: 'L0 8/8/9；L20 8–9/9/10；L60 8–9/9–10/10–11；L100 8–9/9–10/10–11', formula: 'NG / React / Vue / Vanilla，各等级10,000次随机模拟', notes: '16组P10、中位与P90全部位于8–12回合' },
  { category: '目标', key: '精英 / Boss', value: '8–12 / 10–14 个决策', formula: '', notes: '通过技能与阶段而非无限回血延长' },
  { category: '基础', key: '攻击', value: '', formula: '12 + 编码×1.50×centeredScale(编码,0.003,0.94,1.08)', notes: '最少为1，再加功法与装备攻击' },
  { category: '基础', key: '防御', value: '', formula: '架构×0.95×centeredScale(架构,0.0025,0.94,1.07)', notes: '最少为0，再加功法与装备防御' },
  { category: '资源', key: '体力上限', value: '', formula: 'floor(190 + 架构×5.2) + floor(sqrt(精力上限)×3)', notes: '以生命池承载8–12回合基准；精力仍只按平方根反哺体力' },
  { category: '资源', key: '食物/饮水容量', value: '', formula: '200 + 编码×6', notes: '创建角色、读档归一化、物品和世界事件共用唯一公式' },
  { category: '资源', key: '玩家精力上限', value: '', formula: '精力修为 + 装备功法 mpMaxPerLv 加成', notes: '功法上限字段已接入运行时' },
  { category: '资源', key: 'NPC精力上限', value: '', formula: 'floor(内功值×25×架构修正) + 装备功法 mpMaxPerLv 加成', notes: 'NPC 内功值来自基础架构与已装备门派架构功法' },
  { category: '判定', key: '命中率', value: '45%–95%', formula: 'clamp(78% + (攻方思维-守方思维)×0.9% + 命中加成 - 闪避加成)', notes: '减少连续空回合' },
  { category: '判定', key: '减伤率', value: '', formula: '防御/(防御+100)', notes: '递减收益' },
  { category: '判定', key: '招架率', value: '0%–55%', formula: 'clamp(4% + 编码×0.25% + 功法/装备招架)', notes: '招架后保留 60% 伤害' },
  { category: '判定', key: '暴击率', value: '2%–30%', formula: 'clamp(3% + 灵感×0.30% + 装备暴击)', notes: '暴击属性集中到灵感' },
  { category: '技能', key: '招式触发', value: '攻击≤45%；闪避≤27%；招架≤35%', formula: '各类型使用独立 base + count×perMove', notes: '避免多层完全回避锁死战斗' },
  { category: '技能', key: '加力', value: '额外伤害≤75%', formula: '伤害×min(75%, 加力/(加力+100))×随机0.9–1.1', notes: '递减收益，不再直接平铺数百点' },
  { category: 'AI', key: 'NPC 加力', value: '默认 45% 概率、25% 内功', formula: '可由 ai.forceUseRate / forceRatio 覆盖', notes: '高阶人物有爆发但不再每击全力' },
  { category: 'AI', key: 'NPC 摸鱼', value: '默认每战 1 次，最多回 18%', formula: '体力低于35%且精力足够时20%概率', notes: '不会反复重置血条' },
  { category: '恢复', key: '玩家摸鱼 / 用药', value: '每战 1 次 / 2 次', formula: '摸鱼最多恢复20%最大体力', notes: '受保护 HUD 未改，以次数上限约束免费动作' },
  { category: '伤势', key: '战后伤势', value: '单场≤真实体力20%', formula: '净体力损失×15%×(1-功法伤势减免) + 当场重伤', notes: '不按累计受击重复惩罚治疗' },
  { category: '伤势', key: '破相判定', value: '濒死15%；归零30%；每次容貌−20', formula: '两项独立判定且可叠加，仅致命战斗触发', notes: '容貌永久损失会写入角色状态' },
  { category: '战败', key: '资源与功法惩罚', value: '经验/潜能/Token各−5%～10%；25%概率最多一门功法−1级', formula: '三类资源分别随机5%～10%；仅从高于保底等级的已学功法中随机一门', notes: '结算后立即重算派生属性与体力/精力上限' },
  { category: '成长', key: '固定学习经验', value: '全功法Lv1需14；此后逐级增加且始终为偶数', formula: 'Lv1=14；Lv2+=max(偶数幂曲线,14+偶数化((Lv-1)×2×costFactor),前级+2)', notes: '50灵感时1潜能=14经验；costFactor从Lv2起影响斜率；基础前10级为14/16/18/20/22/24/26/28/30/34' },
  { category: '成长', key: '潜能转化学习经验', value: '灵感0/25/50：每潜能8/10/14经验', formula: 'round(10 / clamp(1-(灵感-25)×1.5%,70%,130%))', notes: '每个时间片消耗1潜能；潜能为0且经验未满时不启动研习或进度条' },
  { category: '成长', key: '师父学习学费', value: '本级实际潜能消耗的65%', formula: 'ceil(本级累计潜能消耗×0.65)', notes: '固定经验满后支付；高灵感因潜能消耗更少而同步节省Token' },
  { category: '成长', key: '标准100级路线', value: '811,616经验 / 81,425潜能 / 53,212 Token', formula: '五门基础功法加一门本派架构功法，灵感25', notes: '约71.9小时；灵感50为58,235潜能/38,136 Token/约51.4小时' },
  { category: '成长', key: '持续动作频率', value: '学习10 Hz / 冥想10 Hz / 练功5 Hz', formula: '时间片=1/频率', notes: '学习tick不重复推进全局时钟；冥想与练功按各自时间片推进' },
  { category: '成长', key: '冥想升级边界', value: '修为+1后当前精力=0', formula: '精力满→清零→修为+1→结束本帧补算→下一tick恢复', notes: '长帧剩余累积留到下一帧，不得跨过0直接显示正数' },
  { category: '任务', key: '环任务成长', value: '线性且封顶', formula: '1 + ringGrowth×(环数-1)，再受 growthCap 限制', notes: '悬赏奖励也改为基于初始值线性成长' },
  { category: '任务', key: '奖励互斥', value: '任务奖励或野战奖励二选一', formula: '普通悬赏击杀先标记完成，回程交付时才发奖', notes: '防止同一目标重复获得两份奖励' },
  { category: '任务', key: '交付物退款', value: '固定成本补偿', formula: '物品价格×itemRefundRate', notes: '退款不参与环数成长或随机浮动，服务费才属于奖励' },
  { category: '任务', key: '导师新手项目', value: '50经验 / 50潜能 / 40 Token', formula: '三个项目奖励固定，仅体力消耗分别为25/50/100', notes: '项目难度不再放大奖励' },
  { category: '任务', key: '并行任务状态', value: '不同任务可同时活动', formula: '固定任务按 quest_id；生成任务按 generator:<generator_id> 唯一', notes: '同一 runtime_id/生成器不可重复；任务仅存本局内存，重开或读档时清空' },
  { category: '任务', key: '随机目标过滤', value: '保护任务端点、非战斗与剧情人物', formula: '排除全部任务发布/交付端点、当前目标；击杀池另排除未满18岁、noncombatant、商贩、典当商、师父、显式保护人物', notes: '只有悬赏/击杀环响应击败事件，跑腿与谈话任务必须交付' },
  { category: '人物', key: 'combatRank', value: 'noncombatant→legendary 共7档', formula: '仅缩放生命池与普通奖励', notes: '攻击、防御仍来自显式四维、功法、装备' },
  { category: '人物', key: 'combatRank 生命倍率', value: '0.50 / 0.78 / 0.92 / 1.00 / 1.10 / 1.20 / 1.30', formula: 'noncombatant / novice / trained / veteran / elite / master / legendary', notes: '小学生为noncombatant：1.8架构、0精力时最终100体力' },
  { category: '人物', key: 'combatRank 奖励倍率', value: '0.15 / 0.50 / 0.75 / 1.00 / 1.20 / 1.50 / 2.00', formula: 'noncombatant / novice / trained / veteran / elite / master / legendary', notes: '战斗奖励与生命倍率分离，非战斗人物不成为刷取目标' },
  { category: '人物', key: 'combatRole', value: '7种原型', formula: 'noncombatant/striker/skirmisher/tank/counter/controller/balanced', notes: '66 人四维配点全部唯一且总点数不变' },
  { category: '状态', key: '资源归一化', value: '上限变化即时钳制', formula: '卸功法或战败降级后重算四维、体力与精力上限', notes: '不允许保存当前值高于新上限' },
  { category: '界面', key: '战斗大数值排版', value: '体力与精力支持5–6位数', formula: '双方统计分列显示；伤势百分比独立位于体力条上方', notes: '数值、标签和进度条不得互相覆盖' },
  { category: '界面', key: '顶部进度条宽度', value: '从地图徽标后8px延伸至右边界前16px', formula: 'left=mapBadge.right+8；right=viewportWidth-16', notes: '480逻辑视口下约316px，充分使用右侧空间' },
  { category: '存档', key: 'v5 版本边界', value: '仅接受当前版本', formula: 'version == 5', notes: '资源主键已切换为 UUID；v2、v3、v4 存档全部作废且不迁移' },
];
